# Generated by Django 3.1.1 on 2023-10-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('sex', models.IntegerField(verbose_name='sex')),
                ('age', models.FloatField(verbose_name='age')),
                ('sibsp', models.IntegerField(verbose_name='sibsp')),
                ('parch', models.IntegerField(verbose_name='parch')),
                ('pclass', models.IntegerField(verbose_name='pclass')),
                ('fare', models.FloatField(verbose_name='fare')),
                ('survived', models.FloatField(verbose_name='survived')),
            ],
        ),
    ]
